version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    env_file: .env
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_WARN_ON_HEAD_FAILURE=never
      - WATCHTOWER_NOTIFICATION_URL=gotify://gotify.${DOMAIN_NAME}:443/${GOTIFY_TOKEN}/?priority=${GOTIFY_PRIORITY}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

networks:
  watchtower:
    name: watchtower